### PR TITLE
fix: catch duplicate methods-path in makeJsonSchema

### PR DESCRIPTION
**Pull request by jfet97**
Not sure if I did it correctly, nor how to test it.

### CODE REVIEW

**Comment by patroza** [comment]
Looks rather good. You can run a build and locally link the package to one of our projects or even the boilerplate, then just line up two resources using the same path and method

**Comment by jfet97** [comment]
After struggling with `npm link`, `pnpm link`, and my OS, I finally linked GS to my local version of `effect-app/infra`. However, I encountered errors related to `faker.js` not being loaded, something like that. Frustrated, I manually copied the `dist` version of `makeJsonSchema.js` into GS's `node_modules` folder. Then, I created a duplicate resource to provoke the error I wanted.

Is there a way to make this more readable?

image

**Comment by patroza** [comment]
@jfet97 nice work!
regarding readability; sure, install humanlog, you get a note about that as one of the first log messages on api

**Comment by patroza** [comment]
btw to be more complete we would need to ignore the variable name after :
And few more cases. Maybe good to extract the behavior to a function and write some tests

**Comment by jfet97** [comment]
Yes we could have things like nested paths as well I think:
```
/subscriptions/:id/idk/:subid
```
that is the same as:
```
/subscriptions/:id1/idk/:subid
```
but different than:
```
/subscriptions/:id/idk1/:subid
```

**Comment by jfet97** [comment]
The current logic builds a tree-like data structure to find duplicate paths that make use of the same method. Parameters' names are not relevant, only how many of them are there in a row. Their presence matters, not their name.

Let's say the first path we see is `'/securities/:id/search/:id2'` and the method is `"post"`. Then the structure is initialized as:

```
{
  [methods]: [], // <- first level array for the route '/'
  securities: {
    [methods]: [], // <- array for the route '/securities'
    1: { // <- number of parameters in a row after 'securities'
      [methods]: [], // <- array for the route '/securities/:_'
      search: {
        [methods]: [], // <- array for the route '/securities/:_/search'
        1: { // <- number of parameters in a row after 'search'
           [methods]: ["post"], // <- array for the route '/securities/:_/search/:_'
        }
      }
    }
  }
}
```

If we then encounter any of the following paths: `'/securities/:idt/search/:id2'`, `'/securities/:id/search/:id2t'`, or `'/securities/:idt/search/:id2t'`, and the method is `"post"` again, we will raise an error because the path remains the same; only the names of the parameters have been changed.

Instead, the following paths will be accepted even if the related method is `"post"` again:

* `'/securities/:id/search/'` because there is no parameter at the end
```
// updated tree-like data structure:
{
  [methods]: [], 
  securities: {
    [methods]: [],  
    1: {  
      [methods]: [], 
      search: {
        [methods]: ["post"], // <-
        1: { 
           [methods]: ["post"], 
        }
      }
    }
  }
}
```


*  `'/securities/search/:id2'` because there is no parameter between `securities` and `search`
```
// updated tree-like data structure:
{
  [methods]: [], 
  securities: {
    [methods]: [],  
    1: {  
      [methods]: [], 
      search: {
        [methods]: [],
        1: { 
           [methods]: ["post"], 
        }
      }
    },
    search: { // <-
      [methods]: [],
      1: { 
         [methods]: ["post"], // <-
      }
    }
  }
}
```

* `'/securities/:id/:id2/search/:id3` because there are two parameters between `securities` and `search`
```
// updated tree-like data structure:
{
  [methods]: [], 
  securities: {
    [methods]: [],  
    1: {  
      [methods]: [], 
      search: {
        [methods]: [],
        1: { 
           [methods]: ["post"], 
        }
      }
    },
    2: {  // <-
      [methods]: [], 
      search: {
        [methods]: [],
        1: { 
           [methods]: ["post"], // <-
        }
      }
    }
  }
}
```

The logic has been mainly tested with GS

**Comment by patroza** [comment]
@jfet97 nice work.
can you add `.test.ts` please with the cases?

**Comment by patroza** [comment]
@jfet97 great!
so one thing I was thinking of is that we may want to consider order.
e.g:
`/a/b`
`/a/:something`

should maybe call `Effect.logWarning`, but not error out.
where as
`/a/:something`
`/a/b`

should error out, because `/a/b` will never be reached.
not sure how much complexity we're adding here.

**Comment by jfet97** [comment]
@patroza I'm not sure how the order you are talking about is defined, from the point of view of the final user.

I mean, we write a bunch of files in the `resources` folder where we define the routes, but we do not specify an order between them, do we? Am I missing something? 

And what is the behavior of your architecture when `a/b` is defined before than `a/:smth`? Will `a/b` be matched by `a/b` also after having set the parametric one?

**Comment by patroza** [comment]
@jfet97 the order is defined through mounting order, which is based on the order of controllers and the actions within them.
The behaviour is then standard express behaviour where the first route wins, as the first route that hits and doesn't call `next` stops the pipeline.

But, I guess it is just a bad pattern anyway, and we should maybe stick to not supporting it until we run into a valid use case, but I think that would need a really good reason then.

**Comment by jfet97** [comment]
I was working on it ahahaha @patroza, I'll reopen it and will patch changeset again. I'm almost done

**Comment by patroza** [comment]
> I was working on it ahahaha @patroza, I'll reopen it and will patch changeset again. I'm almost done

the conclusion is not to support the thing I suggested however, whatcha working on? :)

**Comment by jfet97** [comment]
I solved a minor bug with numerical paths, then I was working on the check for shadowed routes. I don't want to loose the work so I'll push it anyway, for the future :P

**Comment by patroza** [comment]
@jfet97 alright, just make a new draft PR for it then.

**Pull request merged**
