### PR TITLE
refine unions with `Q.and` and `Q.where`

### PR DESCRIPTION
**Pull request by jfet97**
This is my attempt to solve https://dev.azure.com/nomizz/Projects/_workitems/edit/565/

The basic idea was to add the following overload to the `and` primitive:

```ts
<
  TFieldValues extends FieldValues,
  TFieldName extends FieldPath<TFieldValues>,
  const V extends FieldPathValue<TFieldValues, TFieldName>
>(
    path: TFieldName,
    value: V
): (
    current: QueryWhere<TFieldValues>
) => QueryWhere<TFieldName extends "_tag" ? Extract<TFieldValues, { _tag: V }> : TFieldValues>
```

But this was causing serious problems in situations like the following one:

```ts
type TestUnion = Person | Animal | Test

const test = make<TestUnion>()
  .pipe(
    where("id", "123"),
    and("_tag", "animal"),
    or(
      where("surname", "john"), // <-- Error: an Animal has no `surname` property
    ),
  )
```

because the `or` primitive would receive a `QueryWhere<Animal>`, that's the correct output of the `and` but prevents us from querying, for example, a person from inside the other path of the `or`.

To solve this I tried to come up with a different primitive for the `or`, something like `or([alt1, alt2])`, but there was a blowup w.r.t. the number of overloads, and the interpreter would need some changes, even though the goal of this PR already works at the value level, but not at the type level.

The solution I came up with is just at the type level and consists of adding a second type arguments to `QueryWhere`: `QueryWhere<Original, 
Refined>`. The `and` primitive may refine the original type, other primitives will propagate both and the primitives related to the projection and the termination of a query will use the refined type, which default is of course the original one.

I hope I got all the types and overloads right 😅

The following is supported too:

```ts
type TestUnion = Person | Animal | Test

const test = make<TestUnion>()
  .pipe(
    where("_tag", "animal"),
  )
```

&nbsp;

### Future work (DONE)

```ts
type TestUnion = Person | Animal | Test

const test = make<TestUnion>()
  .pipe(
    where("id", "123"),
    and("_tag", "animal"),
    or(
      where("surname", "john"),
      and("_tag", "person"),
    ),
  )
```

~~This won't yield a `QueryWhere<TestUnion, Animal | Person>` but a `QueryWhere<TestUnion, TestUnion>` even though the two paths are well typed. Respectively as `QueryWhere<TestUnion, Animal>` the former, `QueryWhere<TestUnion, Person>` the latter.~~

### CODE REVIEW

**Comment by patroza** [comment]
very cool. 
missing changes at the two overloads at; https://github.com/effect-ts-app/libs/blob/main/packages/infra/src/services/RepositoryBase.ts#L101
(as a follow up I would like those upgraded too, so that we can drop having to use flow for the initial chain)

**Comment by jfet97** [comment]
@patroza added but not sure I got them right

**Comment by patroza** [comment]
> @patroza added but not sure I got them right

guess we have to test it. maybe also add the type check tests like in effect repo? then we can do type assertion validation.

btw QueryEnd is also missing passing a type argument for T, meaning TType goes into the R slot.
probably a good idea to remove defaults from type signatures and make them explicit

**Comment by jfet97** [comment]
> btw QueryEnd is also missing passing a type argument for T, meaning TType goes into the R slot.

Can you point me where this is happening?

**Comment by patroza** [comment]
> Can you point me where this is happening?

don't know if its right
Screenshot 2024-10-23 at 11 01 25

**Comment by patroza** [comment]
> anyway there are lot of things that do not play well with this change, I'll try to solve them but I do not have good feelings

I think it's the right path though

**Pull request merged**
