### PR TITLE
Enhance paths check

### PR DESCRIPTION
**Pull request by jfet97**
Not sure how to test `logWarning`

### CODE REVIEW

**Comment by patroza** [comment]
> Not sure how to test `logWarning`

You would need to set a fake logger via `eff.provideSomeLayer(Logger.replace(Logger.defaultLogger, customLogger))` that stores it’s results in an array, then you can evaluate after if you find the message in the array.

**Comment by jfet97** [comment]
For future me: do ask Patrick how to properly write it using effects instead of trickeffects

**Comment by patroza** [comment]
> For future me: do ask Patrick how to properly write it using effects instead of trickeffects

here you go :) effects need to run :)
https://github.com/effect-ts-app/libs/commit/ddaeee3a69f24471bca058b711b85be055b0363d

now I was contemplating just like with validation it may be nice to get all the issues combined, instead of bailing at the first sign of trouble. but then again, it isn't really practically required, this thing is just supposed to inform the user of a dumb mistake, which is better than being unaware, and actually sufficient :)

**Comment by patroza** [comment]
@jfet97 missing changeset, then ready to go from my side

**Comment by jfet97** [comment]
@patroza let's see how many false positive we get this time

**Pull request merged**
